defaults: &defaults
  allow_dynamic_fields: true
  raise_not_found_error: false

development:
  <<: *defaults
  host: 127.0.0.1
  database: startuplab_co_development

test:
  <<: *defaults
  host: 127.0.0.1
  database: startuplab_co_test

# set these environment variables on your prod server
production:
  <<: *defaults
  uri: <%= ENV['MONGOHQ_URL'] %>
  
